# Generated by Django 5.2.7 on 2025-11-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightsearch',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='flightsearch',
            name='origin',
        ),
        migrations.AlterField(
            model_name='flightsearch',
            name='adults',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flightsearch',
            name='children',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flightsearch',
            name='flight_class',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flightsearch',
            name='infants',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flightsearch',
            name='trip_type',
            field=models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')], default='round_trip', max_length=20),
        ),
    ]
